// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB88O0W4eg_Tw0AOvqOfcus6I9ISnSMf2w',
    appId: '1:644510387679:web:c9a347baa3de9b3b45486a',
    messagingSenderId: '644510387679',
    projectId: 'linkedin-clone-bec71',
    authDomain: 'linkedin-clone-bec71.firebaseapp.com',
    storageBucket: 'linkedin-clone-bec71.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtSJi3tGUZTZu3HzV9KZTpr20eCkYPOp8',
    appId: '1:644510387679:android:f6bdd961c09c202f45486a',
    messagingSenderId: '644510387679',
    projectId: 'linkedin-clone-bec71',
    storageBucket: 'linkedin-clone-bec71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlsfYa8QFiuJPyNyoi9uumYhm9euXhIEw',
    appId: '1:644510387679:ios:2613c279ed66aeb045486a',
    messagingSenderId: '644510387679',
    projectId: 'linkedin-clone-bec71',
    storageBucket: 'linkedin-clone-bec71.appspot.com',
    iosBundleId: 'com.example.linkedinClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlsfYa8QFiuJPyNyoi9uumYhm9euXhIEw',
    appId: '1:644510387679:ios:2613c279ed66aeb045486a',
    messagingSenderId: '644510387679',
    projectId: 'linkedin-clone-bec71',
    storageBucket: 'linkedin-clone-bec71.appspot.com',
    iosBundleId: 'com.example.linkedinClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB88O0W4eg_Tw0AOvqOfcus6I9ISnSMf2w',
    appId: '1:644510387679:web:c469e5525786e8ca45486a',
    messagingSenderId: '644510387679',
    projectId: 'linkedin-clone-bec71',
    authDomain: 'linkedin-clone-bec71.firebaseapp.com',
    storageBucket: 'linkedin-clone-bec71.appspot.com',
  );
}
